// <auto-generated />
namespace SistemaAF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Sep30Fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sep30Fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201910011513115_Sep30Fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
