// <auto-generated />
namespace SistemaAF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Sep30Fix2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sep30Fix2));
        
        string IMigrationMetadata.Id
        {
            get { return "201910011610545_Sep30Fix2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
